export const COLOR = {
  Primary_Color: "#4e016b",
  Secondary_Color: "#FA8128",
  Background_Color: "#FFFFFF",
  Text_Color: "#000000",
  light_purple:"#FBFAFE",
  fade_purple:"#EEE8F5",
  white: "#fff",
  black: "#000",
  blue: "#5D5FEE",
  grey: "#BABBC3",
  light: "#F3F4FB",
  darkBlue: "#7978B5",
  red: "red",
};
